In [3]:
import numpy as np
import pandas as pd

In [4]:
# x0  of the intercept(or bias) is initialized to one 
x0 = np.ones(5)
x1 = np.array([1, 3, 5, 7, 9])
X = np.array([x0, x1]).T

y = np.array([1, 3, 4, 3, 5]).T

In [5]:
X

array([[1., 1.],
       [1., 3.],
       [1., 5.],
       [1., 7.],
       [1., 9.]])

In [6]:
y

array([1, 3, 4, 3, 5])

In [7]:
np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

array([1.2, 0.4])